package com.thejoa703.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Mapper;

import com.thejoa703.dto.Recipes3Dto;
import com.thejoa703.dto.RecipesIngre3;
import com.thejoa703.dto.RecipesStep3;

@Mapper
public interface Recipes3Dao {
    // recipes3
    public int insertRecipe(Recipes3Dto recipe);
    public int updateRecipe(Recipes3Dto recipe);
    public int deleteRecipe(int recipeId);
    public Recipes3Dto selectRecipeById(Map<String, Object> params);
    public List<Recipes3Dto> selectRecipeAllPaged(Map<String, Object> params); // rStart, rEnd, category
    public int countSearchRecipes(Map<String, Object> params);
    public List<Recipes3Dto> searchRecipesPaged(Map<String, Object> params); // rStart, rEnd, keyword, searchField, sort, category
    public int incrementViews(int recipeId);
    
    public int countListSearchRecipes(Map<String,Object> params); 
    public List<Recipes3Dto> listSearchRecipesPaged(Map<String,Object> params);
  
    // recipes_ingre3
    public int insertIngre(RecipesIngre3 ingre);
    public int deleteIngreByRecipeId(int recipeId);
    public List<RecipesIngre3> selectIngreByRecipeId(int recipeId);

    // recipes_step3
    public int insertStep(RecipesStep3 step);
    public int deleteStepByRecipeId(int recipeId);
    public List<RecipesStep3> selectStepByRecipeId(int recipeId);

    // likes
    public int insertLike(Map<String, Object> params); // appUserId, recipeId
    public int deleteLike(Map<String, Object> params);
    public int countLikesByRecipe(int recipeId);
    public int existsLike(Map<String, Object> params);

    // search history
    public int insertSearchHistory(Map<String, Object> params); // appUserId, keyword
    public List<Map<String, Object>> topKeywords(int limit);

    // bad words
    public List<String> containsBadWords(String text);
    public int existsBadWord(String word);
    public int insertBadWord(Map<String, Object> params); // wordId generated by selectKey in XML
    public int updateBadWord(Map<String, Object> params); // wordId, newWord
    public int deleteBadWordById(int wordId);
    public int deleteBadWordByWord(String word);
    public List<Map<String, Object>> selectAllBadWords();  
    
    public int countBadWords();
    public List<Map<String,Object>> selectBadWordsPaged(Map<String,Object> params);
    
 // recipes3 상태 변경
    public int updateRecipeStatus(Map<String, Object> param);


    // ai usage
    public int insertAiUsage(Map<String, Object> params); // aiHistId generated by selectKey in XML
    public List<Map<String, Object>> selectAllAiUsage();
    public List<Map<String, Object>> selectAiUsageByUser(int appUserId);
    public int deleteAiUsageById(int aiHistId);
    public int deleteAiUsageByUser(int appUserId);

    // category
    public List<Map<String, Object>> selectAllCategories();
    public String selectCategoryName(int category);
    
    // 내가 작성한 레시피 목록
    public List<Recipes3Dto> selectMyRecipes(int appUserId);
    // 내가 좋아요 표시한 레시피 목록
    public List<Recipes3Dto> selectLikedRecipes(int appUserId);
    
    //관리자용
    // 관리자용 페이징 + 검색
    public List<Recipes3Dto> selectAdminRecipePaged(Map<String,Object> params);
    public int countAdminRecipes(Map<String,Object> params);

    // 관리자용 무조건 삭제
    public int deleteAdminRecipe(int recipeId);
    public int deleteAdminRecipeSteps(int recipeId);
    public int deleteAdminRecipeIngredients(int recipeId);
    public int deleteAdminRecipeLikes(int recipeId);
    
    // 랜덤 추천
    // 카테고리와 키워드를 파라미터로 받아 랜덤 레시피 1개 반환
    public Recipes3Dto selectRandomRecipe(Map<String, Object> params);
}
